### ISSUE TITLE
Mac: cursor needs to move to end of new text after substitution

### ISSUE THREAD

**Issue by meantime** [CharlieHess/electron-text-substitutions#1]
I have this substitution:

`/hi` -> `I'm Chris, greetings from Slack HQ in San Francisco.`

After I typed the input the cursor was left just after the 'm' in "I'm" rather than at the end.

**Comment by CharlieHess** [comment]
Fixed in https://github.com/CharlieHess/electron-text-substitutions/commit/6f2e103d902be510b010e6c48f7edd75f7e4241f.
