### ISSUE TITLE
Handle contenteditable

### ISSUE THREAD

**Issue by CharlieHess** [CharlieHess/electron-text-substitutions#11]
We can't rely on `.value` for, say, a `div` with `contenteditable` set. We need to rely on `innerHTML` or something similar.

**Comment by simonvallee** [comment]
Oh man, Andrew Schmidt just realized this busts automatic curly quotes and apostrophes in the message input. So yeah, this is a big deal now. ;)

**Comment by CharlieHess** [comment]
#12 & https://github.com/CharlieHess/electron-text-substitutions/pull/13 make this much better.
